# Generated by Django 3.2.4 on 2021-07-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCurrent',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
                ('background_current', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DriverBehaviour',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EV',
            fields=[
                ('ev_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('current', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConfiguration',
            fields=[
                ('network_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('solar_panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cable_spec', models.IntegerField()),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.networkconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_charge_x', models.IntegerField()),
                ('total_charge_y', models.FloatField()),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('connections', models.ManyToManyField(blank=True, related_name='_SimulatorAPI_node_connections_+', through='SimulatorAPI.Connections', to='SimulatorAPI.Node')),
                ('network_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.networkconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='networkconfiguration',
            name='substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.node'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='HouseEVs',
            fields=[
                ('house_ev_id', models.AutoField(primary_key=True, serialize=False)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.ev')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.house')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='EVs',
            field=models.ManyToManyField(related_name='evs', through='SimulatorAPI.HouseEVs', to='SimulatorAPI.EV'),
        ),
        migrations.AddField(
            model_name='house',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimulatorAPI.node'),
        ),
        migrations.AddField(
            model_name='connections',
            name='connection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='SimulatorAPI.node'),
        ),
        migrations.AddField(
            model_name='connections',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='SimulatorAPI.node'),
        ),
        migrations.CreateModel(
            name='ChargeProfile',
            fields=[
                ('charge_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField(default=1)),
                ('y', models.FloatField(default=1)),
                ('ev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='SimulatorAPI.ev')),
            ],
        ),
    ]
