version: "3"
services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: env('DATABASE_NAME')
      MYSQL_ROOT_PASSWORD: env('DATABASE_PASS')
    volumes:
      - ./database/mysql/db:/var/lib/mysql
    networks:
      - db-net


  backend:
    build:
      context: ./EVChargingSimulator
    command : gunicorn EVChargingSimulator.wsgi --bind 0.0.0.0:8000
    env_file:
      - ./EVChargingSimulator/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net
  frontend:
    build:
      context: ./front-end
    volumes:
      - frontend_build:/front-end/build
    networks:
      - db-net
    stdin_open: true
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/front-end
    depends_on:
      - backend
      - frontend
    networks:
      - db-net
volumes:
  frontend_build:
networks:
  db-net:
